import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { ChevronRight, Database } from "lucide-react";
import { PieChart, Pie, Cell, ResponsiveContainer } from "recharts";
import { SectionHeader } from "@/components/insights/SectionHeader";
import { StatusChip } from "@/components/insights/StatusChip";

const pieData = [
  { name: "You", value: 4.2 },
  { name: "Competitors", value: 6.8 }
];

const COLORS = ["hsl(163 82% 36%)", "hsl(252 76% 66%)"];

interface InsightCardProps {
  icon: string;
  title: string;
  bgClass: string;
  priority: "critical" | "high" | "medium";
  dataSource: string;
  children: React.ReactNode;
  actionLabel?: string;
  onAction?: () => void;
  onShowData?: () => void;
}

const InsightCard = ({ 
  icon, 
  title, 
  bgClass, 
  priority,
  dataSource,
  children, 
  actionLabel, 
  onAction, 
  onShowData 
}: InsightCardProps) => (
  <Card className={`p-5 border-2 ${bgClass} hover:shadow-card-hover transition-all duration-300 relative`}>
    <div className="absolute top-3 right-3 flex items-center gap-1">
      {onShowData && (
        <Button 
          variant="ghost" 
          size="sm" 
          className="h-7 w-7 p-0 opacity-60 hover:opacity-100"
          onClick={onShowData}
          title="View underlying data"
        >
          <Database className="w-3.5 h-3.5" />
        </Button>
      )}
    </div>
    
    <div className="space-y-3">
      <div className="flex items-start gap-3">
        <span className="text-2xl">{icon}</span>
        <div>
          <StatusChip type={priority} className="mb-1" />
          <h4 className="font-semibold text-foreground">{title}</h4>
        </div>
      </div>
      
      <div className="text-sm text-muted-foreground space-y-2">
        {children}
      </div>

      <div className="text-[10px] text-muted-foreground border-t border-border/50 pt-2 mt-2">
        📊 {dataSource}
      </div>
      
      {actionLabel && onAction && (
        <Button 
          variant="outline" 
          size="sm" 
          onClick={onAction}
          className="w-full border-primary/30 hover:bg-primary/10 gap-1"
        >
          {actionLabel}
          <ChevronRight className="w-3 h-3" />
        </Button>
      )}
    </div>
  </Card>
);

export const KeyInsightsGrid = () => {
  return (
    <div className="space-y-4">
      <SectionHeader
        level={3}
        title="Actionable Strategy Insights"
        subtitle="AI-generated recommendations with expected impact"
        timeRange="Last 7 days"
        dataScope="5 competitors"
        sampleSize="127 videos • 847 posts"
        tooltip="Each insight is generated by analyzing competitor patterns and your performance gaps. Click data icon to see underlying metrics."
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {/* Card 1: Hook Duration */}
        <InsightCard
          icon="🚀"
          title="Shorten Hook Duration"
          bgClass="border-destructive/20 bg-destructive/5"
          priority="critical"
          dataSource="45 competitor videos with 10M+ views"
          actionLabel="Generate hooks like top competitors"
          onAction={() => console.log("Regenerate hooks")}
          onShowData={() => console.log("Show data")}
        >
          <p>
            <strong>@topcompetitor</strong> gained 5.2% followers via short hooks (under 15s). 
            Your avg duration: <strong>28s</strong>—shorten for +12% views.
          </p>
          <div className="bg-background/50 rounded p-2 text-xs">
            <strong>Top 3 hook patterns:</strong> Question (38%), Shock (31%), Emotional (24%)
          </div>
        </InsightCard>

        {/* Card 2: Engagement Gap */}
        <InsightCard
          icon="📊"
          title="Engagement Gap Analysis"
          bgClass="border-yellow-500/20 bg-yellow-500/5"
          priority="high"
          dataSource="Aggregated ER across 3 platforms • 183 videos"
          actionLabel="See platform-specific actions"
          onAction={() => console.log("View breakdown")}
          onShowData={() => console.log("Show data")}
        >
          <div className="flex items-center gap-4">
            <ResponsiveContainer width={80} height={80}>
              <PieChart>
                <Pie
                  data={pieData}
                  cx="50%"
                  cy="50%"
                  innerRadius={20}
                  outerRadius={35}
                  paddingAngle={5}
                  dataKey="value"
                >
                  {pieData.map((_, index) => (
                    <Cell key={`cell-${index}`} fill={COLORS[index]} />
                  ))}
                </Pie>
              </PieChart>
            </ResponsiveContainer>
            <div className="flex-1 space-y-1">
              <div>Your ER: <strong>4.2%</strong> vs Competitor Avg: <strong>6.8%</strong></div>
              <div className="text-xs flex items-center gap-1 flex-wrap">
                <Badge variant="secondary" className="text-[10px] bg-destructive/10 text-destructive">
                  -38% gap
                </Badge>
                <span>TikTok has highest competitor ER (12.1%)</span>
              </div>
            </div>
          </div>
        </InsightCard>

        {/* Card 3: Virality Patterns */}
        <InsightCard
          icon="🎯"
          title="High-Virality Content Patterns"
          bgClass="border-accent/20 bg-accent/5"
          priority="medium"
          dataSource="Top 10 viral videos from competitors • Last 30 days"
          actionLabel="Find winning video patterns"
          onAction={() => console.log("Analyze videos")}
          onShowData={() => console.log("Show data")}
        >
          <div className="space-y-2">
            <div className="flex items-center justify-between">
              <span>Top videos: 87-92% virality score</span>
              <Badge variant="secondary" className="bg-accent/10 text-accent text-[10px]">
                +15% above avg
              </Badge>
            </div>
            <div className="flex gap-2">
              {[1, 2, 3].map((i) => (
                <div 
                  key={i}
                  className="flex-1 h-14 bg-muted rounded-md flex items-center justify-center cursor-pointer hover:ring-2 hover:ring-primary transition-all"
                >
                  <span className="text-xs text-muted-foreground">Video {i}</span>
                </div>
              ))}
            </div>
            <p className="text-xs bg-background/50 rounded p-2">
              <strong>Pattern:</strong> Educational hooks + fashion niche + emotional storytelling
            </p>
          </div>
        </InsightCard>

        {/* Card 4: Posting Times */}
        <InsightCard
          icon="⏰"
          title="Shift Posting Schedule"
          bgClass="border-primary/20 bg-primary/5"
          priority="high"
          dataSource="847 competitor posts • ER by posting hour"
          onShowData={() => console.log("Show data")}
        >
          <p>
            Competitors with highest ER post during <strong>18:00-21:00</strong> (UTC+1). 
            Your current schedule peaks at <strong>14:00</strong> (UTC+1).
          </p>
          <div className="grid grid-cols-3 gap-2 pt-1">
            <div className="bg-muted rounded p-2 text-center">
              <div className="font-semibold text-foreground text-sm">18:00-21:00</div>
              <div className="text-[10px] text-muted-foreground">Optimal</div>
            </div>
            <div className="bg-muted rounded p-2 text-center">
              <div className="font-semibold text-foreground text-sm">14:00</div>
              <div className="text-[10px] text-muted-foreground">Your Peak</div>
            </div>
            <div className="bg-accent/10 rounded p-2 text-center">
              <div className="font-semibold text-accent text-sm">+18%</div>
              <div className="text-[10px] text-muted-foreground">Potential ER lift</div>
            </div>
          </div>
        </InsightCard>

        {/* Card 5: Quick Win */}
        <InsightCard
          icon="⚡"
          title="Quick Win: Increase Content Frequency"
          bgClass="border-yellow-500/20 bg-yellow-500/5 md:col-span-2"
          priority="critical"
          dataSource="7-day posting cadence analysis • Top 5 competitors"
          onShowData={() => console.log("Show data")}
        >
          <div className="flex flex-col md:flex-row md:items-center gap-4">
            <div className="flex-1">
              <p>
                You post <strong>2.3/day</strong> vs top performers' <strong>8-10/day</strong> (77% gap). 
                Test increasing to 5/day for 30 days.
              </p>
              <p className="text-xs mt-2 text-muted-foreground">
                Correlation analysis shows 0.78 correlation between posting frequency and follower growth rate among top performers.
              </p>
            </div>
            <div className="bg-accent/10 rounded-lg p-3 text-center shrink-0">
              <div className="text-lg font-bold text-accent">+25-40%</div>
              <div className="text-xs text-muted-foreground">Expected reach increase</div>
            </div>
          </div>
        </InsightCard>
      </div>
    </div>
  );
};
